// <auto-generated />
namespace ContactManagerWithGenericRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullabledat3e : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullabledat3e));
        
        string IMigrationMetadata.Id
        {
            get { return "201508312022132_nullabledat3e"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
